[package]
name = "tokio-trace-subscriber"
version = "0.0.1"
authors = ["Eliza Weisman <eliza@buoyant.io>"]

[dependencies]
tokio-trace-core = "0.2"

[dev-dependencies]
tokio-trace-log = { path = "../tokio-trace-log" }
